const translations = {
  "pt-BR": {
    about: "Sobre",
    skills: "Habilidades",
    education: "Formação",
    projects: "Projetos",
    heroText: "Olá,<br>Sou o <strong>Luan Marques</strong>,<br>atualmente estou estudando para me<br>tornar um <strong>Engenheiro de Software</strong>.",
    aboutTitle: "Sobre Mim",
    aboutText1: "Meu nome é Luan Marques, tenho 25 anos e sou formado em Análise e Desenvolvimento de Sistemas. Já explorei várias áreas da tecnologia — como Front-end, Banco de Dados e até DevOps — mas foi em Engenharia de Software que realmente me encontrei.",
    aboutText2: "Descobrir que é possível tirar uma ideia do papel e transformá-la em algo real com programação foi o que me fez me apaixonar de vez por essa área.",
    skillsTitle: "Habilidades",
    educationTitle: "Formação",
    educationCourse: "Curso de Graduação Superior de Tecnologia em Análise e Desenvolvimento de Sistemas",
    educationInstitution: "Faculdade Unopar",
    projectsTitle: "Projetos",
    projectInDev: "PROJETO EM DESENVOLVIMENTO",
    btnCV: "CV",
  },
  "en-US": {
    about: "About",
    skills: "Skills",
    education: "Education",
    projects: "Projects",
    heroText: "Hello,<br>I'm <strong>Luan Marques</strong>,<br>currently studying to become a <strong>Software Engineer</strong>.",
    aboutTitle: "About Me",
    aboutText1: "My name is Luan Marques, I'm 25 years old and I have a degree in Systems Analysis and Development. I've explored several areas of technology — such as Front-end, Databases, and even DevOps — but it was in Software Engineering that I truly found myself.",
    aboutText2: "Discovering that it's possible to take an idea off paper and turn it into something real through programming is what made me fall in love with this field once and for all.",
    skillsTitle: "Skills",
    educationTitle: "Education",
    educationCourse: "Bachelor's Degree in Systems Analysis and Development",
    educationInstitution: "Unopar College",
    projectsTitle: "Projects",
    projectInDev: "PROJECT UNDER DEVELOPMENT",
    btnCV: "Resume",
  },
  "ja-JP": {
    about: "私について",
    skills: "スキル",
    education: "学歴",
    projects: "プロジェクト",
    heroText: "こんにちは、<br>私は <strong>Luan Marques</strong> です。<br><strong>ソフトウェアエンジニア</strong>を目指して勉強中です。",
    aboutTitle: "自己紹介",
    aboutText1: "私はLuan Marques、25歳で、システム分析と開発の学位を取得しています。フロントエンド、データベース、DevOpsなど、さまざまな分野を経験してきましたが、ソフトウェアエンジニアリングの分野で本当に自分の道を見つけることができました。",
    aboutText2: "アイデアを紙の上から現実のものへと変えることがプログラミングで可能だと気づいたとき、この分野に強く魅了されました。",
    skillsTitle: "スキル",
    educationTitle: "学歴",
    educationCourse: "システム分析と開発の学士号",
    educationInstitution: "Unopar大学",
    projectsTitle: "プロジェクト",
    projectInDev: "開発中のプロジェクト",
    btnCV: "履歴書",
  }
};
